""" Script to test download_archive data
@author Jessica Tanon

JAN 2019
"""

import unittest
import parse_latex as pl
import logging
import sys

logging.basicConfig(level="INFO")

try:
    ORIG1 = open("../resources/ex1_original.tex", 'r').read()
    EXP1 = open("../resources/ex1_expected.tex", 'r').read()
    ORIG2 = open("../resources/ex2_original.tex", 'r').read()
    EXP2 = open("../resources/ex2_expected.tex", 'r').read()
except IOError as e:
    sys.exit("Missing test files, cannot run tests: {}".format(e))


class TestParser(unittest.TestCase):

    def test_sections_extractor_ex1(self):
        expected_sections = [
            "\section{Introduction}",
            "\section{Related Work}",
            "\section{Model}",
            "\subsection{Input and Embedding Layers}",
            "\subsection{LSTM Layer}",
            "\subsection{Task-Specific Attention Layer}",
            "\subsection{Regularization Layer}",
            "\section{Experiments}",
            "\subsection{Datasets}",
            "\subsection{Comparison Methods}",
            "\subsection{Results}",
            "\section{Conclusion}"
        ]

        extracted_sections = [e[1] for e in pl.get_sections(ORIG1)]
        self.assertListEqual(expected_sections, extracted_sections)

    def test_sections_extractor_ex2(self):
        expected = [
            "\section{Introduction}",
            "\paragraph{Multi-source abstractive summarization based RC.}",
            "\paragraph{Style-controllable RC.}",
            "\section{Problem Formulation}",
            "\section{Proposed Model}",
            "\subsection{Question-Passages Reader}",
            "\paragraph{Transformer encoder block.}",
            "\subsection{Passage Ranker}",
            "\subsection{Answer Possibility Classifier}",
            "\subsection{Answer Sentence Decoder}",
            "\paragraph{Transformer decoder block.}",
            "\paragraph{Extended vocabulary distribution.}",
            "\paragraph{Copy distribution.}",
            "\paragraph{Final distribution.}",
            "\subsection{Loss Function}",
            "\section{Experiments}",
            "\subsection{Setup}",
            "\paragraph{Datasets and styles.}",
            "\paragraph{Model configurations.}",
            "\paragraph{Optimizer.}",
            "\paragraph{Regularization.}",
            "\subsection{Results}",
            "\paragraph{Does our model achieve state-of-the-art performance for generative RC?}",
            "\paragraph{Does our multi-style learning improve NLG performance?}",
            "\paragraph{Does our Transformer-based pointer-generator improve NLG performance?}",
            "\paragraph{Does our joint learning with the ranker and classifier improve NLG performance?}",
            "\paragraph{Does our joint learning improve the passage re-ranking performance?}",
            "\paragraph{Does our model accurately identify answerable questions?}",
            "\paragraph{Does our model accurately control answers with different styles?}",
            "\paragraph{Error analysis.}",
            "\section{Related Work and Discussion}",
            "\paragraph{RC with NLG.}",
            "\paragraph{Controllable text generation.}",
            "\paragraph{Multi-passage RC.}",
            "\paragraph{RC with unanswerable question identification.}",
            "\paragraph{Abstractive summarization.}",
            "\section{Conclusion}",
            "\section{Reading Comprehension Examples generated by Masque from MS MARCO 2.1}"
        ]

        extracted = [e[1] for e in pl.get_sections(ORIG2)]
        self.assertListEqual(expected, extracted)

    def test_extract_all_ex1(self):
        extracted_content = pl.get_all(ORIG1)
        self.assertEqual(extracted_content, EXP1)

    def test_extract_all_ex2(self):
        self.maxDiff = None
        extracted_content = pl.get_all(ORIG2)
        self.assertEqual(extracted_content, EXP2)

